### ISSUE TITLE
How to get the Coord after moving the map?

### ISSUE THREAD

**Issue by danicarla** [xguaita/Leaflet.MapCenterCoord#10]
Hi Guys Maybe it's a simple question

But I would like to capture the coords and put in a hidden field.. 
Can anyone help me?

**Comment by robertjoellewis** [comment]
I am a newb too. I think there is a getCenter() function you can use though with leaflet. I haven't made it that far yet :)

Does this help (see link below)? The getCenter() function is listed in there.

 http://leafletjs.com/reference-1.2.0.html

**Comment by danicarla** [comment]
Tks! :)
