### ISSUE TITLE
Zoom in or out, change the coordinates of the center of the map

### ISSUE THREAD

**Issue by distrasser** [xguaita/Leaflet.MapCenterCoord#12]
If the map is created on negative latitud or longitude, using the control to zoom in or to zoom out,  set the map center at the absolute values of latitud and longitud, so moving the center of the map far away.
I create the map this way:
```
    var map = L.map('map').setView([-34.91355 , -55.04537], 9);

    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    L.control.mapCenterCoord().addTo(map);
```
I would appreciate if you help me solve this problem.

Maybe this two facts is helpful for solver this bug: 

1. If i first pan the map and then zoom in the map, works fine.
2. Zoom in or zoom out with mouse wheel also works fine

**Comment by Perbr0430009** [comment]
I didn't take time to read the code, just removed the Math.abs() parts of _getLatLngCoord() on line 42.

Probably need more testing. But it solved my problem and didn't break anything yet.

**Comment by distrasser** [comment]
thank you, that solve the problem
