### ISSUE TITLE
Test on Leaflet 1.0.0

### ISSUE THREAD

**Issue by IvanSanchez** [xguaita/Leaflet.MapCenterCoord#2]
Please test on Leaflet 1.0.0-beta2 and write a note in the project's README about compatibility with Leaflet versions.

**Comment by xguaita** [comment]
[leaflet1](/xguaita/Leaflet.MapCenterCoord/tree/leaflet1) branch was created to test on Leaflet 1.0.0
Examples work fine with the beta2 version
